name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build_pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    name: Build (PR)
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build

  deploy_main:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Deploy (main)
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          ###### Repository/Build Configurations ######
          app_location: "/"          # Root contains package.json and Vite config
          api_location: ""           # not using Azure Functions
          output_location: "dist"    # Vite outputs here
          ###### End of Repository/Build Configurations ######
